### ISSUE TITLE
MY TOKEN LOST

### ISSUE THREAD

**Issue by WAEL1125** [anyswap/Anyswap-Audit#10]
I sent FTM ERC20 from ETH Mainnet to FTM Opera Chain; but they have never arrived at my FTM Opera.

**Comment by mutulong** [comment]
I sent FTM ERC20 from ETH Mainnet to FTM Opera Chain too, never arrived, are we scammed

**Comment by stellarcheck** [comment]
did you get resolve the issue? I have the same issue now.
