### ISSUE TITLE
Multichain.xyz

### ISSUE THREAD

**Issue by tjodc10** [anyswap/Anyswap-Audit#11]
Tried swapping 600 FTM from eth network to the phantom network yesterday. It shows the transaction complete 14 hours ago but no coins in my metamask. Dang it! I haven't been scammed until now for almost 3 years!

**Comment by tjodc10** [comment]
It just showed up! Sweeeet!

**Comment by AlirezaVR** [comment]
Hi. 
Yesterday 25 November I tried to send 1542.212 FTM from eth network to phantom network, now my FTMs are gone and I dont recive any FTM on ftm network.... PLZ help

**Comment by djfrez** [comment]
I swapped 246 FTM from eth network to phantom on Nov 25, paid the absurd eth gas fee and nothing happened except subtract the gas fee. What's going on???
