### ISSUE TITLE
Txn >$200k not going through (even after 12 hours)

### ISSUE THREAD

**Issue by kalogreen** [anyswap/Anyswap-Audit#2]
Sending a txn over $200k says it "can take up to 12 hours". 12 hours has now passed and even though assets were removed on Eth mainnet, they have not been transferred back into my wallet on the BSC network. 

How can I contact someone directly to provide further details and resolve this issue ASAP? 

Thanks for any help.

**Comment by ivanbb17** [comment]
> Sending a txn over $200k says it "can take up to 12 hours". 12 hours has now passed and even though assets were removed on Eth mainnet, they have not been transferred back into my wallet on the BSC network. 
> 
> 
> 
> How can I contact someone directly to provide further details and resolve this issue ASAP? 
> 
> 
> 
> Thanks for any help.

Bro did you resolved? I have the same problem

**Comment by ivanbb17** [comment]
> hi mate how did your issue end ? i have the same problem thank you

Bro, finally did you resolved?

**Comment by zhaojun-sh** [comment]
All bridge transactions arrived. Please check on explorer https://anyswap.net
