### ISSUE TITLE
Cannot redeem my FTM swapped from MultichainXYZ

### ISSUE THREAD

**Issue by JungKim777** [anyswap/Anyswap-Audit#3]
I tried to swap my FTM(ETH) to FTM(FTM) (~80K USD)
After processing two transaction, it kepts showing 'Depositing~~~' and then suddenly my Metamask became disconnected from it.
I really hope i would redeem my FTM back.

- TXN hash #1("approve") : 0x02850c73de8e1d97543a3eb8c4e32834e1b80e5b9e01cfb7344338e8b5c932e7
- TXN hash #2("swapout") : 0x2e8f906798c7b3f2b8e3646de3b32fc89c08823570cd46c7864768704485b5fb

![image](https://user-images.githubusercontent.com/83468899/116730170-236f3500-aa23-11eb-9566-130c93f6c10e.png)

 
![image](https://user-images.githubusercontent.com/83468899/116730064-fa4ea480-aa22-11eb-8935-ab4168df80dd.png)

**Comment by hchenri** [comment]
Hi mate i have exactly the same issue did you sort it out ?

**Comment by JungKim777** [comment]
> Hi mate i have exactly the same issue did you sort it out ?

hot yet... so frustrated

**Comment by JungKim777** [comment]
waited about 12hrs and finally i got it.
