### ISSUE TITLE
Swap incomplete

### ISSUE THREAD

**Issue by Jordanbhiebert** [anyswap/Anyswap-Audit#4]
I attempted to swap FTM from Eth mainnet to FTM mainnet and it was got cancelled and my FTM dissapeared

**Comment by ivanbb17** [comment]
hi, i have the same problem, what do you do? did you solved?

**Comment by Jordanbhiebert** [comment]
I just left it, it appeared in my opera mainnet after a couple days, I'll leave this up in case other people have issues. Not sure how long each may take to free up but I think it is common

**Comment by ivanbb17** [comment]
Nice, thanks bro... definitely is a long way fund a FTM wallet

**Comment by HoangHa77** [comment]
i have transferred banana from bsc network to matic network wallet address 0x02DB9d41bd3cF1aB4A175929ABaDAe820DB62d58 but it has been more than 2 hours and still not received, please explain why to me...!

**Comment by zhaojun-sh** [comment]
All bridge transactions arrived. Please check on explorer https://anyswap.net
