### ISSUE TITLE
Lost funds

### ISSUE THREAD

**Issue by ivanbb17** [anyswap/Anyswap-Audit#5]
I make a swap of FTM in eth mainnet, to Opera mainnet, the swap show the message that's complete, but I I don't have my FTM in my Opera Wallet..... pls I need help with this problem

when I clicked on the final message that I was ready to see the txn ... it appeared to me as if it did not exist

**Comment by HoangHa77** [comment]
I have transferred banana from bsc network to matic network wallet address 0x02DB9d41bd3cF1aB4A175929ABaDAe820DB62d58, but more than 2 hours ago but still not received, can you please explain to me, when will banana return to my matic network wallet...!

**Comment by zhaojun-sh** [comment]
All bridge transactions arrived. Please check on explorer https://anyswap.net
