### ISSUE TITLE
FTM Funds lost

### ISSUE THREAD

**Issue by rktgt** [anyswap/Anyswap-Audit#6]
I transferred 23779 FTM from Eth mainnet to Opera Mainnet. Its been over 10 hours and I still don't see the funds in my Opera Wallet. Its been deducted from the Eth wallet though. Where are my funds? When will it be available?

**Comment by HoangHa77** [comment]
I have transferred banana from bsc network to matic network wallet address 0x02DB9d41bd3cF1aB4A175929ABaDAe820DB62d58, but more than 2 hours ago but still not received, can you please explain to me, when will banana return to my matic network wallet...!

**Comment by caothuan1975** [comment]
I have transferred 146 banana from bsc network to matic network wallet address 0x9888091DEf85d894C1Eb072e011678765A4f9EBb, but more than 1 hours ago but still not received, can you please explain to me, when will banana return to my matic network wallet...! please help me. Thanks

**Comment by zhaojun-sh** [comment]
All bridge transactions arrived. Please check on explorer https://anyswap.net
