### ISSUE TITLE
资金损失

### ISSUE THREAD

**Issue by hani-web** [anyswap/Anyswap-Audit#7]
I failed to convert the USDT cross-chain of the Ethereum chain to the USDT of FANTOM. All the assets disappeared without being withdrawn

**Comment by zhaojun-sh** [comment]
All bridge transactions arrived. Please check on explorer https://anyswap.net

**Comment by c1cio** [comment]
odd this string just ahowed up in my inbox and has a pinned message from
8:31am that I cant save or do anything with
