### ISSUE TITLE
lost funds using multichain.xyz

### ISSUE THREAD

**Issue by 34reptile** [anyswap/Anyswap-Audit#9]
I sent FTM ERC20 from ETH Mainnet to FTM Opera Chain.  The transfer says success but it has a different receiving address after the bridge/swap.  Why is that if multichain.xyz have connected on my wallet alone? Are my funds totally gone now?

**Comment by zerlinazz** [comment]
same issue here......

**Comment by zerlinazz** [comment]
I also sent FTM ERC20 from ETH Mainnet to FTM Opera Chain; but they have never arrived at my FTM Opera. The transfer has a different receiving address after the swap too.

**Comment by 34reptile** [comment]
Sadly, it looks like we all got scammed!

**Comment by WAEL1125** [comment]
I sent FTM ERC20 from ETH Mainnet to FTM Opera Chain; but they have never arrived at my FTM Opera. The transfer has a different receiving address after the swap

**Comment by mutulong** [comment]
I sent FTM ERC20 from ETH Mainnet to FTM Opera Chain too, never arrived, are we scammed?

**Comment by luka16kay** [comment]
Hi everyone, I finally received my funds like 36 hours later. Maybe it's because of a lack of liquidity. Hope you guys will receive all your funds, be patient.

**Comment by ddk671** [comment]
Sadly, it looks like we all got scammed!
